version: '3.9'

services:
  minio:
    image: quay.io/minio/minio
    platform: linux/amd64
    container_name: minio
    command: "server /data --console-address \":9090\""
    restart: always
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9090
    volumes:
      - ~/.motor-on-premise-data/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}

